{{- if and .Values.enabled .Values.services }}
apiVersion: batch/v1
kind: Job
metadata:
  name: idam-service-importer
  labels:
    app.kubernetes.io/name: idam-service-importer
    app.kubernetes.io/instance: {{ .Release.Name }}-idam-service-importer
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "5"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  template:
    metadata:
      name: idam-service-importer
      labels:
        app.kubernetes.io/name: idam-service-importer
    spec:
      containers:
        {{- $self := . -}}
        {{- range $index, $item := .Values.services }}
        - name: idam-service-importer-{{ $index }}
          image: hmctspublic.azurecr.io/hmcts/idam/utils:latest
          command: [ /scripts/create-service.sh ]
          args:
            - {{ .label | quote }}
            - {{ .selfRegistrationAllowed | default false | quote }}
            - {{ .clientID | quote }}
            - {{ .clientSecret | quote }}
            - {{ printf "[%s]" (.redirectURL | quote) | quote }}
            - {{ printf "[%s]" (.allowedRole | default "" | quote) | quote }}
          env:
            - name: IDAM_API_URL
              value: http://idam-api
            - name: IDAM_ADMIN_USER
              value: {{ $self.Values.global.adminUser }}
            - name: IDAM_ADMIN_PASSWORD
              value: {{ $self.Values.global.adminPassword }}
          resources:
            requests:
              cpu: 125m
              memory: 8Mi
            limits:
              cpu: 250m
              memory: 16Mi
          imagePullPolicy: IfNotPresent
        {{- end }}
      restartPolicy: Never
{{- end }}