idam-service-importer:
  enabled: true
  services:
    - label: CCD
      clientID: ccd_gateway
      clientSecret: ccd_gateway_secret
      redirectURL: http://localhost:3451/oauth2redirect
    - label: fpl
      clientID: fpl
      clientSecret: OOOOOOOOOOOOOOOO
      redirectURL: https://localhost:9000/oauth2/callback
