apiVersion: v1
description: A Helm chart for HMCTS Java Microservices
icon: https://github.com/hmcts/chart-java/raw/master/images/icons8-java-50.png
keywords:
- java
- web
- springboot
- postgres
- postgresql
name: java
version: 2.11.2
