tags:
  fpl-ccd-stack: true
  ccd-idam-pr: true

java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    IDAM_API_URL: http://api-fpl-sidam-preview.service.core-compute-preview.internal
    CORE_CASE_DATA_API_URL: http://${SERVICE_NAME}-data-store-api
    LOCAL_AUTHORITY_USER_MAPPING: SA=>03131803-1732-43ca-a2b2-ff5d230cd53e,92551c3f-d3db-4dc0-ba21-c26c22dde03a,16e20279-a9c6-4906-9ffa-d68bc0e8f626;HN=>fc814447-030d-4677-bfc6-50f4b91f06fa,3cfa218f-4f7e-4a32-b7e4-152eba66e6b6
  keyVaults:
    fpl:
      resourceGroup: fpl-case-service
      secrets:
        - notify-api-key
        - docmosis-api-key
        - fpl-case-service-s2s-secret
        - local-authority-email-to-code-mapping
        - local-authority-code-to-name-mapping
        - local-authority-user-mapping
        - local-authority-code-to-hmcts-court-mapping
        - local-authority-code-to-cafcass-mapping

ccd:
  ingressHost: ${SERVICE_FQDN}
  ingressIP: ${INGRESS_IP}
  consulIP: ${CONSUL_LB_IP}
  idamApiUrl: http://api-fpl-sidam-preview.service.core-compute-preview.internal
  idamWebUrl: http://web-fpl-sidam-preview.service.core-compute-preview.internal
  idam-pr:
    releaseNameOverride: ${SERVICE_NAME}-ccd-idam-pr
    api:
      url: http://api-fpl-sidam-preview.service.core-compute-preview.internal
    redirect_uris:
      CCD:
        - https://case-management-web-${SERVICE_FQDN}/oauth2redirect
  caseManagementWeb:
    enabled: true
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      DM_URL: https://gateway-${SERVICE_FQDN}/documents
      DM_URL_REMOTE: https?://(gateway-${SERVICE_FQDN}:443|dm-store-aat.service.core-compute-aat.internal)/documents
      CCD_ACTIVITY_URL: null
  apiGateway:
    s2sKey: ${CCD_API_GATEWAY_S2S_SECRET}
    idamClientSecret:
      value: ${CCD_API_GATEWAY_IDAM_CLIENT_SECRET}
    environment:
      PROXY_DOCUMENT_MANAGEMENT: http://dm-store-aat.service.core-compute-aat.internal
      ADDRESS_LOOKUP_TOKEN: ${ADDRESS_LOOKUP_TOKEN}
  definitionStoreApi:
    s2sKey: ${CCD_DEFINITION_STORE_S2S_SECRET}
  dataStoreApi:
    s2sKey: ${CCD_DATA_STORE_S2S_SECRET}
