tags:
  fpl-ccd-stack: true
  ccd-idam-pr: true

java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  livenessDelay: 50
  environment:
    IDAM_API_URL: http://api-idam-fpl.service.core-compute-preview.internal
    CORE_CASE_DATA_API_URL: http://${SERVICE_NAME}-data-store-api
    IDAM_CLIENT_ID: fpl_case_service
    IDAM_CLIENT_REDIRECT_URI: https://localhost:9000/oauth2/callback
  keyVaults:
    fpl:
      resourceGroup: fpl-case-service
      secrets:
        - notify-api-key
        - docmosis-api-key
        - fpl-case-service-s2s-secret
        - fpl-case-service-idam-client-secret-preview
        - local-authority-email-to-code-mapping
        - local-authority-code-to-name-mapping
        - local-authority-user-mapping-preview
        - local-authority-code-to-hmcts-court-mapping
        - local-authority-code-to-cafcass-mapping
        - system-update-user-username
        - system-update-user-password

ccd:
  ingressHost: ${SERVICE_FQDN}
  ingressIP: ${INGRESS_IP}
  consulIP: ${CONSUL_LB_IP}
  cpuRequests: 250m
  idamApiUrl: http://api-idam-fpl.service.core-compute-preview.internal
  idamWebUrl: http://web-idam-fpl.service.core-compute-preview.internal
  idam-pr:
    releaseNameOverride: ${SERVICE_NAME}-ccd-idam-pr
    api:
      url: http://api-idam-fpl.service.core-compute-preview.internal
    redirect_uris:
      CCD:
        - https://case-management-web-${SERVICE_FQDN}/oauth2redirect
  caseManagementWeb:
    enabled: true
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      DM_URL: https://gateway-${SERVICE_FQDN}/documents
      DM_URL_REMOTE: https?://(gateway-${SERVICE_FQDN}:443|dm-store-aat.service.core-compute-aat.internal)/documents
      CCD_ACTIVITY_URL: null
  apiGateway:
    s2sKey: ${CCD_API_GATEWAY_S2S_SECRET}
    idamClientSecret:
      value: ccd_gateway_secret
    environment:
      PROXY_DOCUMENT_MANAGEMENT: http://dm-store-aat.service.core-compute-aat.internal
      ADDRESS_LOOKUP_TOKEN: ${ADDRESS_LOOKUP_TOKEN}
  definitionStoreApi:
    s2sKey: ${CCD_DEFINITION_STORE_S2S_SECRET}
  dataStoreApi:
    s2sKey: ${CCD_DATA_STORE_S2S_SECRET}
